## Adds ngQuill as a dependency of ikApp.

assets:
  js:
    - bundles/itkquilleditor/assets/libs/quill.min.js
    - bundles/itkquilleditor/assets/libs/ng-quill.min.js
  css:
    - bundles/itkquilleditor/css/quill.core.css
    - bundles/itkquilleditor/css/quill.snow.css
  js_prod_assets:
    - bundles/itkquilleditor/assets/libs/quill.min.js
    - bundles/itkquilleditor/assets/libs/ng-quill.min.js

modules:

apps:
  ikApp:
    dependencies:
      - ngQuill
